/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deliverycontrol.view;


import javax.imageio.ImageIO;
import javax.swing.*;

import com.mycompany.deliverycontrol.CRUD.IRegistraClienteCRUD;
import com.mycompany.deliverycontrol.CRUD.IRegistraEntregadoresCRUD;
import com.mycompany.deliverycontrol.CRUD.IRegistraPedidoCRUD;
import com.mycompany.deliverycontrol.controller.RegistraClienteControle;
import com.mycompany.deliverycontrol.controller.RegistraEntregadoresControle;
import com.mycompany.deliverycontrol.controller.RegistraPedidoControle;
import com.mycompany.deliverycontrol.model.Cliente;
import com.mycompany.deliverycontrol.model.Entregador;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;

/**
 *
 * @author Gustavo Camargo
 */
public class TelaPedidos extends javax.swing.JFrame {

        /**
         * Creates new form TelaCadastroCliente
         */
        IRegistraPedidoCRUD pedidos;
        IRegistraClienteCRUD clientes;
        IRegistraEntregadoresCRUD entregadores;
        ArrayList<Entregador> entregadorLista;
        
        public TelaPedidos() {
                initComponents();
                pedidos = new RegistraPedidoControle();
                clientes = new RegistraClienteControle();
                entregadores = new RegistraEntregadoresControle();
                this.setTitle("Registrar pedido");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                jComboBox_buscaCliente.addItem("");
                jComboBox_buscaCliente.addItem("ID");
                //jComboBox_buscaCliente.addItem("Nome");
                jComboBox_buscaCliente.setSelectedIndex(0);
                jTextField_buscaCliente.setEditable(false);
                jTextField_clienteNome.setEditable(false);
                jTextField_enderecoCliente.setEditable(false);
                jTextField_telefoneCliente.setEditable(false);

                try {
                    entregadorLista = entregadores.listagemDeEntregador();
                    preencherComboBoxEntregador();
                }catch (Exception e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
        }

    String urlDaImagem = "https://www.segredes.com.br/deliverycontrol/img/dc-pequeno.png";
    // Baixar a imagem da internet e criar um ImageIcon
    ImageIcon icon = criarImageIcon(urlDaImagem);
    public static ImageIcon criarImageIcon(String url) {
        try {
            // Carregar a imagem a partir do URL
            BufferedImage imagem = ImageIO.read(new URL(url));

            // Criar um ImageIcon a partir da imagem
            return new ImageIcon(imagem);
        } catch (IOException e) {
            // Tratar exceções de IO, por exemplo, URL inválido ou problema de conexão
            e.printStackTrace();
            return null; // Retornar null em caso de erro
        }
    }

    private void preencherComboBoxEntregador() throws Exception {
        jComboBox_Motoqueiro.removeAllItems();
        jComboBox_Motoqueiro.addItem("Escolha o Entregador:");
        for (Entregador entregador : entregadorLista) {
            jComboBox_Motoqueiro.addItem(entregador.getNome());
        }
    }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton_Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_pedidos = new javax.swing.JTable();
        jButton_salvarPedido = new javax.swing.JButton();
        jButton_limparPedido = new javax.swing.JButton();
        jComboBox_statusPedido = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 31, 21));
        jPanel1.setForeground(new java.awt.Color(65, 31, 21));

        jLabel1.setBackground(new java.awt.Color(255, 178, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 178, 0));
        jLabel1.setText("Pedidos");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo delivery pequeno.png"))); // NOI18N

        jButton_Voltar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton_Voltar.setText("Voltar");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        jTable_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Entregador"
            }
        ));
        jScrollPane1.setViewportView(jTable_pedidos);

        jButton_salvarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_salvarPedido.setText("Salvar");
        jButton_salvarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salvarPedidoActionPerformed(evt);
            }
        });

        jButton_limparPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_limparPedido.setText("Limpar");
        jButton_limparPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparPedidoActionPerformed(evt);
            }
        });

        jComboBox_statusPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 680, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_salvarPedido)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_limparPedido))
                    .addComponent(jComboBox_statusPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Voltar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)))
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_statusPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_salvarPedido)
                            .addComponent(jButton_limparPedido)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(65, 31, 21));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        TelaPrincipalUser telaPrincipalUser = new TelaPrincipalUser();
        telaPrincipalUser.dispose();
        telaPrincipalUser.setLocationRelativeTo(this);
        telaPrincipalUser.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        telaPrincipalUser.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

        /**
         * @param evt
         */

        // #region
        private void jButton_BuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_BuscaClienteActionPerformed
                if (jComboBox_buscaCliente.getSelectedIndex() == 1) {
                        try {
                                Cliente cliente = clientes
                                                .consultar(Integer.valueOf(jTextField_buscaCliente.getText()));
                                jTextField_clienteNome.setText(cliente.getNome());
                                jTextField_enderecoCliente.setText(cliente.getEndereco());
                                jTextField_telefoneCliente.setText(cliente.getTelefone());
                                System.out.println(cliente.toString());
                        } catch (Exception e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                        }
                } else if (jComboBox_buscaCliente.getSelectedIndex() == 2) {
                        try {
                                Cliente cliente = clientes.consultarPorNome(jTextField_buscaCliente.getText());
                                jTextField_clienteNome.setText(cliente.getNome());
                                jTextField_enderecoCliente.setText(cliente.getEndereco());
                                jTextField_telefoneCliente.setText(cliente.getTelefone());
                                System.out.println(cliente.toString());
                        } catch (Exception e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                        }
                }

        }// GEN-LAST:event_jButton_BuscaClienteActionPerformed

        private void jTextField_buscaClienteKeyTyped(java.awt.event.KeyEvent evt) {
                try {   
                        String caracteres = "0123456789";
                        if (jComboBox_buscaCliente.getSelectedIndex() == 1) {                                
                                if (!caracteres.contains(evt.getKeyChar() + "")) {
                                        evt.consume();
                                }
                        }else if(jComboBox_buscaCliente.getSelectedIndex() == 2){
                                if (caracteres.contains(evt.getKeyChar() + "")) {
                                        evt.consume();
                                } 
                        }
                } catch (Exception erro) {
                        JOptionPane.showMessageDialog(this, erro.getMessage());
                }

        }

        private void jTextField_buscaClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_buscaClienteActionPerformed

        }// GEN-LAST:event_jTextField_buscaClienteActionPerformed

        private void jComboBox_buscaClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox_buscaClienteActionPerformed
                if (jComboBox_buscaCliente.getSelectedIndex() != 0) {
                        jTextField_buscaCliente.setEditable(true);
                } else {
                        jTextField_buscaCliente.setText("");
                        jTextField_buscaCliente.setEditable(false);

                }
        }// GEN-LAST:event_jComboBox_buscaClienteActionPerformed

        private void jButton_registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_registrarClienteActionPerformed
                TelaCadastroCliente telaCliente = new TelaCadastroCliente();
                telaCliente.setVisible(true);
        }// GEN-LAST:event_jButton_registrarClienteActionPerformed

        private void jButton_salvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_salvarPedidoActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton_salvarPedidoActionPerformed

        private void jButton_limparPedidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_limparPedidoActionPerformed
                limpaCampos();
        }// GEN-LAST:event_jButton_limparPedidoActionPerformed

        public void limpaCampos() {
                jTextField_buscaCliente.setText(null);
                jTextField_clienteNome.setText(null);
                jTextField_enderecoCliente.setText(null);
                jTextField_telefoneCliente.setText(null);
                jComboBox_buscaCliente.setSelectedIndex(0);
                jComboBox_Motoqueiro.setSelectedIndex(0);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new TelaPedidos().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JButton jButton_limparPedido;
    private javax.swing.JButton jButton_salvarPedido;
    private javax.swing.JComboBox<String> jComboBox_statusPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_pedidos;
    // End of variables declaration//GEN-END:variables
}
