/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deliverycontrol.view;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import com.mycompany.deliverycontrol.CRUD.IRegistraClienteCRUD;
import com.mycompany.deliverycontrol.CRUD.IRegistraEntregadoresCRUD;
import com.mycompany.deliverycontrol.CRUD.IRegistraPedidoCRUD;
import com.mycompany.deliverycontrol.controller.RegistraClienteControle;
import com.mycompany.deliverycontrol.controller.RegistraEntregadoresControle;
import com.mycompany.deliverycontrol.controller.RegistraPedidoControle;
import com.mycompany.deliverycontrol.model.Cliente;

/**
 *
 * @author Gustavo Camargo
 */
public class TelaRegistrarPedido extends javax.swing.JFrame {

        /**
         * Creates new form TelaCadastroCliente
         */
        IRegistraPedidoCRUD pedidos;
        IRegistraClienteCRUD clientes;
        IRegistraEntregadoresCRUD entregadores;

        public TelaRegistrarPedido() {
                initComponents();
                pedidos = new RegistraPedidoControle();
                clientes = new RegistraClienteControle();
                entregadores = new RegistraEntregadoresControle();
                this.setTitle("Registrar pedido");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                jComboBox_buscaCliente.addItem("");
                jComboBox_buscaCliente.addItem("ID");
                jComboBox_buscaCliente.addItem("Nome");
                jComboBox_buscaCliente.setSelectedIndex(0);
                jTextField_buscaCliente.setEditable(false);
                jTextField_clienteNome.setEditable(false);
                jTextField_enderecoCliente.setEditable(false);
                jTextField_telefoneCliente.setEditable(false);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jTextField_enderecoCliente = new javax.swing.JTextField();
                jTextField_telefoneCliente = new javax.swing.JTextField();
                jButton_salvarPedido = new javax.swing.JButton();
                jButton_limparPedido = new javax.swing.JButton();
                jButton_BuscaCliente = new javax.swing.JButton();
                jTextField_clienteNome = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea_descricaoPedido = new javax.swing.JTextArea();
                jComboBox_buscaCliente = new javax.swing.JComboBox<>();
                jTextField_buscaCliente = new javax.swing.JTextField();
                jButton_registrarCliente = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(65, 31, 21));
                jPanel1.setForeground(new java.awt.Color(65, 31, 21));

                jLabel1.setBackground(new java.awt.Color(255, 178, 0));
                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 178, 0));
                jLabel1.setText("Registrar Pedido");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel6)
                                                                .addGap(36, 36, 36)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(19, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                40,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel6))
                                                                .addContainerGap()));

                jPanel2.setBackground(new java.awt.Color(65, 31, 21));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Cliente:");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Endereco:");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Descrição Pedido:");

                jButton_salvarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButton_salvarPedido.setText("Salvar");
                jButton_salvarPedido.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_salvarPedidoActionPerformed(evt);
                        }
                });

                jButton_limparPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButton_limparPedido.setText("Limpar");
                jButton_limparPedido.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_limparPedidoActionPerformed(evt);
                        }
                });

                jButton_BuscaCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButton_BuscaCliente.setText("Buscar");
                jButton_BuscaCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_BuscaClienteActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Buscar Cliente:");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("Telefone:");

                jTextArea_descricaoPedido.setColumns(20);
                jTextArea_descricaoPedido.setRows(5);
                jScrollPane2.setViewportView(jTextArea_descricaoPedido);

                jComboBox_buscaCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jComboBox_buscaCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox_buscaClienteActionPerformed(evt);
                        }
                });

                jTextField_buscaCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField_buscaClienteActionPerformed(evt);
                        }
                });

                jButton_registrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButton_registrarCliente.setText("Registrar novo");
                jButton_registrarCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_registrarClienteActionPerformed(evt);
                        }
                });

                jTextField_buscaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                jTextField_buscaClienteKeyTyped(evt);
                        }
                });
                // #region gerado automatico
                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(40, 40, 40)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(jLabel2))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(jTextField_clienteNome,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jTextField_telefoneCliente,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jTextField_enderecoCliente,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                520,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel5)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(jComboBox_buscaCliente,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(jTextField_buscaCliente,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                163,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jButton_BuscaCliente)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jButton_registrarCliente,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel4)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(jScrollPane2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                491,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jButton_salvarPedido)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(jButton_limparPedido)))))
                                                                .addContainerGap(198, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(62, 62, 62)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton_BuscaCliente)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jComboBox_buscaCliente,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField_buscaCliente,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jButton_registrarCliente))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jTextField_clienteNome,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jTextField_enderecoCliente,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jTextField_telefoneCliente,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel7))
                                                                .addGap(44, 44, 44)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel4))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton_salvarPedido)
                                                                                .addComponent(jButton_limparPedido))
                                                                .addContainerGap(95, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param evt
         */

        // #region
        private void jButton_BuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_BuscaClienteActionPerformed
                if (jComboBox_buscaCliente.getSelectedIndex() == 1) {
                        try {
                                Cliente cliente = clientes
                                                .consultar(Integer.valueOf(jTextField_buscaCliente.getText()));
                                jTextField_clienteNome.setText(cliente.getNome());
                                jTextField_enderecoCliente.setText(cliente.getEndereco());
                                jTextField_telefoneCliente.setText(cliente.getTelefone());
                                System.out.println(cliente.toString());
                        } catch (Exception e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                        }
                } else if (jComboBox_buscaCliente.getSelectedIndex() == 2) {
                        try {
                                Cliente cliente = clientes.consultarPorNome(jTextField_buscaCliente.getText());
                                jTextField_clienteNome.setText(cliente.getNome());
                                jTextField_enderecoCliente.setText(cliente.getEndereco());
                                jTextField_telefoneCliente.setText(cliente.getTelefone());
                                System.out.println(cliente.toString());
                        } catch (Exception e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                        }
                }

        }// GEN-LAST:event_jButton_BuscaClienteActionPerformed

        private void jTextField_buscaClienteKeyTyped(java.awt.event.KeyEvent evt) {
                try {   
                        String caracteres = "0123456789";
                        if (jComboBox_buscaCliente.getSelectedIndex() == 1) {                                
                                if (!caracteres.contains(evt.getKeyChar() + "")) {
                                        evt.consume();
                                }
                        }else if(jComboBox_buscaCliente.getSelectedIndex() == 2){
                                if (caracteres.contains(evt.getKeyChar() + "")) {
                                        evt.consume();
                                } 
                        }
                } catch (Exception erro) {
                        JOptionPane.showMessageDialog(this, erro.getMessage());
                }

        }

        private void jTextField_buscaClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_buscaClienteActionPerformed

        }// GEN-LAST:event_jTextField_buscaClienteActionPerformed

        private void jComboBox_buscaClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox_buscaClienteActionPerformed
                if (jComboBox_buscaCliente.getSelectedIndex() != 0) {
                        jTextField_buscaCliente.setEditable(true);
                } else {
                        jTextField_buscaCliente.setText("");
                        jTextField_buscaCliente.setEditable(false);

                }
        }// GEN-LAST:event_jComboBox_buscaClienteActionPerformed

        private void jButton_registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_registrarClienteActionPerformed
                TelaCadastroCliente_1 telaCliente = new TelaCadastroCliente_1();
                telaCliente.setVisible(true);
        }// GEN-LAST:event_jButton_registrarClienteActionPerformed

        private void jButton_salvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_salvarPedidoActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton_salvarPedidoActionPerformed

        private void jButton_limparPedidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_limparPedidoActionPerformed
                limpaCampos();
        }// GEN-LAST:event_jButton_limparPedidoActionPerformed

        public void limpaCampos() {
                jTextField_buscaCliente.setText(null);
                jTextField_clienteNome.setText(null);
                jTextField_enderecoCliente.setText(null);
                jTextField_telefoneCliente.setText(null);
                jComboBox_buscaCliente.setSelectedIndex(0);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(TelaRegistrarPedido.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new TelaRegistrarPedido().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton_BuscaCliente;
        private javax.swing.JButton jButton_limparPedido;
        private javax.swing.JButton jButton_registrarCliente;
        private javax.swing.JButton jButton_salvarPedido;
        private javax.swing.JComboBox<String> jComboBox_buscaCliente;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea_descricaoPedido;
        private javax.swing.JTextField jTextField_buscaCliente;
        private javax.swing.JTextField jTextField_clienteNome;
        private javax.swing.JTextField jTextField_enderecoCliente;
        private javax.swing.JTextField jTextField_telefoneCliente;
        // End of variables declaration//GEN-END:variables
}
